import { ClerkProvider } from "@clerk/nextjs";
import { type Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/shared/navbar";
import { ThemeProvider } from "@/components/shared/theme-provider";
import ClickSpark from "@/components/ui/click-spark";

const apparat = localFont({
  src: "./fonts/apparat-semi-condensed-regular.otf",
  variable: "--font-apparat",
});

const franktion = localFont({
  src: "./fonts/PPFraktionMono-Bold.otf",
  variable: "--font-franktion",
});

const sohne = localFont({
  src: "./fonts/TestSohneBreit-Buch.otf",
  variable: "--font-sohne",
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};
``;
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider publishableKey="pk_test_ZGVmaW5pdGUtY2xhbS05NC5jbGVyay5hY2NvdW50cy5kZXYk">
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${apparat.variable} ${franktion.variable} ${sohne.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ClickSpark
              sparkSize={10}
              sparkRadius={15}
              sparkCount={8}
              duration={400}
            >
              <Navbar />
              {children}
            </ClickSpark>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
