import { ClerkProvider } from "@clerk/nextjs";
import { type Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/navbar";
import { ThemeProvider } from "@/components/shared/theme-provider";
import ClickSpark from "@/components/ui/click-spark";
import { Footer } from "@/components/shared/footer";

const workSans = localFont({
  src: "./fonts/worksans.ttf",
  variable: "--font-work-sans",
});

const franktion = localFont({
  src: "./fonts/PPFraktionMono-Bold.otf",
  variable: "--font-franktion",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};
``;
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider publishableKey="pk_test_ZGVmaW5pdGUtY2xhbS05NC5jbGVyay5hY2NvdW50cy5kZXYk">
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${workSans.variable} ${franktion.variable} ${inter.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ClickSpark
              sparkSize={10}
              sparkRadius={15}
              sparkCount={8}
              duration={400}
            >
              <Navbar />
              {children}
              <Footer />
            </ClickSpark>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
